### ISSUE TITLE
How to visualize results in rviz?

### ISSUE THREAD

**Issue by chowkamlee81** [tigerk0430/voxelnet_ros#2]
I subscribed topics 
/velodyne_points_modified
BoundingBox  from jsk_rviz_plugins
BoundingBoxArray from jsk_rviz_plugins

Now how to view results of vehicle detection bounding box on rviz. Kindly help me please on this issue.

**Comment by gyubeomim** [comment]
If you install all packages from jsk,
(`sudo apt-get install ros-kinetic-jsk*`)
there is rviz plugin you can visualize.

open RViz --> add --> by display type --> jsk_rviz_plugins --> BoundingBoxArray

and click it, then It's registered in your display tab.
and click it again, you can set the topic of this message type. and type `voxelnet_arr_bbox` 
then the detecting boxes will show up :-)

**Comment by chowkamlee81** [comment]
Thanks @tigerk0430 , got the solution as per your procedure. Able to view outputs....
